# Site settings
title: jeffrey kwan
email: jeffreyjkwan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffrey-kwan.com" # the base hostname & protocol for your site
twitter_username: jeffuree
github_username:  jeffreykwan

# Build settings
markdown: kramdown
