# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffrey-kwan.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Jeffrey Kwan
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "jeffrey kwan blog" # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: 'jeffreykwan/'
  google_plus:
  instagram:
  linkedin: 'https://www.linkedin.com/in/jeffreyjkwan'
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: 'UA-67243310-1'
  disqus_shortname:
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Open+Sans:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jemoji
# Rake Generator Settings
post:
  template: |
    ---
    title:
    layout: post
    ---
page:
  template: |
    ---
    title:
    layout: pag
    ---
editor: atom
